// <auto-generated />
using System;
using BookMyHome.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyHome.Persistence.Migrations
{
    [DbContext(typeof(BookMyHomeDbContext))]
    [Migration("20260924082037_AddAccommodationImages")]
    partial class AddAccommodationImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.Property<Guid>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AccommodationId");

                    b.HasIndex("HostId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Beach Road 1",
                            HostId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Beach House",
                            PricePerNight = 1200m
                        },
                        new
                        {
                            AccommodationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Main Street 10",
                            HostId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "City Apartment",
                            PricePerNight = 850m
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.AccommodationImage", b =>
                {
                    b.Property<Guid>("AccommodationImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationImageId");

                    b.HasIndex("AccommodationId");

                    b.ToTable("AccommodationImages");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BookingId");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateOnly(2027, 6, 5),
                            StartDate = new DateOnly(2027, 6, 1)
                        },
                        new
                        {
                            BookingId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateOnly(2027, 7, 15),
                            StartDate = new DateOnly(2027, 7, 10)
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Host", b =>
                {
                    b.HasBaseType("BookMyHome.Domain.Models.User");

                    b.HasDiscriminator().HasValue("Host");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "host@bookmyhome.dk",
                            Name = "Test Host"
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Host", "Host")
                        .WithMany("Accommodations")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.AccommodationImage", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Accommodation", "Accommodation")
                        .WithMany("Images")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Booking", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Accommodation", "Accommodation")
                        .WithMany("Bookings")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Host", b =>
                {
                    b.Navigation("Accommodations");
                });
#pragma warning restore 612, 618
        }
    }
}
