// <auto-generated />
using System;
using BookMyHome.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyHome.Persistence.Migrations
{
    [DbContext(typeof(BookMyHomeDbContext))]
    partial class BookMyHomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.Property<Guid>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Beach House"
                        },
                        new
                        {
                            AccommodationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "City Apartment"
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BookingId");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateOnly(2027, 6, 5),
                            StartDate = new DateOnly(2027, 6, 1)
                        },
                        new
                        {
                            BookingId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AccommodationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateOnly(2027, 7, 15),
                            StartDate = new DateOnly(2027, 7, 10)
                        });
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Booking", b =>
                {
                    b.HasOne("BookMyHome.Domain.Models.Accommodation", "Accommodation")
                        .WithMany("Bookings")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("BookMyHome.Domain.Models.Accommodation", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
